version: '3.9'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8000
    command: npm run dev

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SECRET_KEY=dev-secret-key-for-local-development
      - DEBUG=True
      - DB_NAME=coptic_social_dev
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=db-dev
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db-dev
    command: python manage.py runserver 0.0.0.0:8000

  db-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coptic_social_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data

volumes:
  dev_postgres_data: 