# Generated by Django 4.2.7 on 2025-06-13 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parishevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parishevent',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='parishes.parish'),
        ),
        migrations.AddField(
            model_name='parish',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_parishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='parishes.diocese'),
        ),
        migrations.AddField(
            model_name='diocese',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_dioceses', to=settings.AUTH_USER_MODEL),
        ),
    ]
